// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_ra1vxYg4xfFpWLalYe6-tpSELQDFl9k',
    appId: '1:663977562435:web:cc1635739685ae48705ff6',
    messagingSenderId: '663977562435',
    projectId: 'bazaar-sy',
    authDomain: 'bazaar-sy.firebaseapp.com',
    storageBucket: 'bazaar-sy.appspot.com',
    measurementId: 'G-HBR4QTVH83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp0BS_BKh4f-dE039BVRaA1UExgw-D8TA',
    appId: '1:663977562435:android:ef68c14603c3c3b7705ff6',
    messagingSenderId: '663977562435',
    projectId: 'bazaar-sy',
    storageBucket: 'bazaar-sy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEJGLrfdyow5MU5JgtgbQ61xKBQk_axQQ',
    appId: '1:663977562435:ios:da6711827f9a0b4d705ff6',
    messagingSenderId: '663977562435',
    projectId: 'bazaar-sy',
    storageBucket: 'bazaar-sy.appspot.com',
    iosClientId: '663977562435-0kv3hnh6kgsbaiq9b9qtvtse3kcmompe.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceMuzamil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEJGLrfdyow5MU5JgtgbQ61xKBQk_axQQ',
    appId: '1:663977562435:ios:da6711827f9a0b4d705ff6',
    messagingSenderId: '663977562435',
    projectId: 'bazaar-sy',
    storageBucket: 'bazaar-sy.appspot.com',
    iosClientId: '663977562435-0kv3hnh6kgsbaiq9b9qtvtse3kcmompe.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceMuzamil',
  );
}
